-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.0.99.2
-- Module  Version: 5.7
-- Mon Mar 20 11:11:04 2017

-- parameterized module component declaration
component xo3lstarter_clkgen_50_12
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : xo3lstarter_clkgen_50_12
    port map (CLKI=>__, CLKOP=>__, LOCK=>__);
